language: go
go:
    - 1.9

go_import_path: github.com/versent/unicreds

install:
    - echo noop

env:
    - "PATH=/home/travis/gopath/bin:$PATH"

script:
    - go get -u github.com/golang/lint/golint
    - go get -u golang.org/x/tools/cmd/goimports
    - go get -u github.com/golang/dep/cmd/dep
    - golint ./...
    - make updatedeps
    - make test

matix:
    fast_finish: true
    allow_failures:
        - go: tip
